### PR TITLE
Traditional/Simplified Chinese and Russian Translation 

### PR DESCRIPTION
**Pull request by AngelofMe**

### CODE REVIEW

**Comment by AngelofMe** [comment]
cecb709 (Russian) isn't translated by me

**Comment by AngelofMe** [comment]
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-ja/strings.xml
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-ru/strings.xml
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-zh-rCN/strings.xml
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-zh-rTW/strings.xml

**Comment by AngelofMe** [comment]
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-ja/strings.xml
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-ru/strings.xml
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-zh-rCN/strings.xml
https://github.com/AngelofMe/vvb/blob/main/app/src/main/res/values-zh-rTW/strings.xml

**Comment by AngelofMe** [comment]
En OK
Ru ОК
they're different
Control + F (Find in Page) "OK" and "ОК"
ОК is Russian
OK is English

**Comment by AngelofMe** [comment]
also А (Russian) and A (English) are different

**Comment by AngelofMe** [comment]
I was going to translate italian, spanish, french, german, but my english is too bad so i gave up

**Comment by AngelofMe** [comment]
The lines are now in English, can they be removed?  
Will this reduce the size of the App?

1    <string name="app_name">Virtual Virtual Boy</string>

12    <string name="load_game_from_file_explanation_button">OK</string>

49-60     <string name="input_menu_dpad_left">Left D-Pad</string>
    <string name="input_menu_dpad_right">Right D-Pad</string>
    <string name="input_menu_button_left">Left</string>
    <string name="input_menu_button_right">Right</string>
    <string name="input_menu_button_up">Up</string>
    <string name="input_menu_button_down">Down</string>
    <string name="input_menu_button_a">A</string>
    <string name="input_menu_button_b">B</string>
    <string name="input_menu_button_lt">L Trigger</string>
    <string name="input_menu_button_rt">R Trigger</string>
    <string name="input_menu_button_start">Start</string>
    <string name="input_menu_button_select">Select</string>
    
85     <string name="video_menu_invalid_colors_button">OK</string>

**Comment by AngelofMe** [comment]
How about this?
I don't know what will happen because I've never used Android Studio
ja/tw/cn/ru strings.xml
<s>
    <string name="app_name">Virtual Virtual Boy</string>
    
    <string name="load_game_from_file_explanation_button">OK</string>
    
    <string name="input_menu_dpad_left">Left D-Pad</string>
    <string name="input_menu_dpad_right">Right D-Pad</string>
    <string name="input_menu_button_left">Left</string>
    <string name="input_menu_button_right">Right</string>
    <string name="input_menu_button_up">Up</string>
    <string name="input_menu_button_down">Down</string>
    <string name="input_menu_button_a">A</string>
    <string name="input_menu_button_b">B</string>
    <string name="input_menu_button_lt">L Trigger</string>
    <string name="input_menu_button_rt">R Trigger</string>
    <string name="input_menu_button_start">Start</string>
    <string name="input_menu_button_select">Select</string>
    
    <string name="video_menu_invalid_colors_button">OK</string>
</s>

**Comment by AngelofMe** [comment]
How about this?
I don't know what will happen because I've never used Android Studio
ja/tw/cn/ru strings.xml
<s>
    <string name="app_name">Virtual Virtual Boy</string>
    
    <string name="load_game_from_file_explanation_button">OK</string>
    
    <string name="input_menu_dpad_left">Left D-Pad</string>
    <string name="input_menu_dpad_right">Right D-Pad</string>
    <string name="input_menu_button_left">Left</string>
    <string name="input_menu_button_right">Right</string>
    <string name="input_menu_button_up">Up</string>
    <string name="input_menu_button_down">Down</string>
    <string name="input_menu_button_a">A</string>
    <string name="input_menu_button_b">B</string>
    <string name="input_menu_button_lt">L Trigger</string>
    <string name="input_menu_button_rt">R Trigger</string>
    <string name="input_menu_button_start">Start</string>
    <string name="input_menu_button_select">Select</string>
    
    <string name="video_menu_invalid_colors_button">OK</string>
</s>

**Comment by SupernaviX** [comment]
Hello, and thank you!

Sorry I'm so slow to respond during the week, lately I've only had energy to work on this on weekends.

When you added [res/values-ja/strings.xml](https://github.com/SupernaviX/vvb/blob/main/app/src/main/res/values-ja/strings.xml), you gave the app some strings that it can use in the "ja" context (on a phone when it's running in Japanese). If there's any strings that aren't in `res/values-ja/strings.xml`, the app will use strings from the "default" context instead. Those "default" values are whatever is in [res/values/strings.xml](https://github.com/SupernaviX/vvb/blob/main/app/src/main/res/values/strings.xml), which in this app are the English translations.

So yeah, if you leave values out of the russian/chinese/etc translation files then the app will use the English value instead. It will be a few bytes smaller; not small enough that it makes much of a difference, but it will be smaller.

**Comment by AngelofMe** [comment]
Please give me some time, I need to improve and re-translate it recently. I have found a teacher who is better than me in translating some common words

**Pull request closed without merging**
